# Generated by Django 4.2 on 2023-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='', verbose_name='Название')),
                ('datetime', models.DateTimeField(default='2023-22-04 12:29:34', verbose_name='Дата публикации')),
                ('categories', models.CharField(choices=[('Techonology', 'Techonology'), ('Celebrity', 'Celebrity')], max_length=20, null='', verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
